export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO'
export const OBTENER_SECTORES = 'OBTENER_SECTORES'
export const SECTOR_ACTUAL = 'SECTOR_ACTUAL'

export const PUESTOS_SECTOR = 'PUESTOS_SECTOR'
export const OBTENER_PUESTOS = 'OBTENER_PUESTOS'
export const OBTENER_PUESTO = 'OBTENER_PUESTO'

//RECURSOS

export const OBTENER_RECURSOS = 'OBTENER_RECURSOS'
export const RECURSOS_CATEGORIA = 'RECURSOS_CATEGORIA'
export const CATEGORIA_ACTUAL = 'CATEGORIA_ACTUAL'

//Autenticacion

export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CERRAR_SESION = 'CERRAR_SESION'
