export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO'
export const OBTENER_SECTORES = 'OBTENER_SECTORES'
export const SECTOR_ACTUAL = 'SECTOR_ACTUAL'

export const PUESTOS_SECTOR = 'PUESTOS_SECTOR'
export const OBTENER_PUESTOS = 'OBTENER_PUESTOS'
export const OBTENER_PUESTO = 'OBTENER_PUESTO'

//RECURSOS

export const OBTENER_RECURSOS = 'OBTENER_RECURSOS'
export const RECURSOS_CATEGORIA = 'RECURSOS_CATEGORIA'
export const CATEGORIA_ACTUAL = 'CATEGORIA_ACTUAL'